---
- name: Add ElasticSearch repo apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add ElasticSearch apt repo.
  apt_repository:
    repo: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
    state: present
  notify:
    - reload systemd

- name: Install ElasticSearch.
  apt:
    name: elasticsearch
    state: latest
  notify:
    - reload systemd
    - restart elasticsearch

- name: Configure ElasticSearch.
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: 'cluster\.name:'
      line: 'cluster.name: {{ elk_cluster_name }}'
    - regexp: 'network\.host:'
      line: 'network.host: "localhost"'
    - regexp: 'bootstrap\.mlockall:'
      line: 'bootstrap.mlockall: true'
      # Force presence of snapshot config line, even though snapshots are disabled by default.
      # Doing this to prevent a failed snapshot action on the first attempt, since the handlers
      # will not have been run yet. Flushing the handlers may be a more elegant solution.
    - regexp: 'path\.repo:'
      line: 'path.repo: {{ elasticsearch_snapshot_directory }}'
  notify:
    - restart elasticsearch

- name: Start elasticsearch service.
  service:
    name: elasticsearch
    state: running

