---
- name: Add Logstash repo apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash apt repo.
  apt_repository:
    repo: "deb http://packages.elastic.co/logstash/2.1/debian stable main"
    state: present

- name: Install Logstash.
  apt:
    name: logstash
    state: latest
  notify:
    - reload systemd config
    - restart logstash

- name: Create Logstash config directories.
  file:
    path: "/etc/logstash/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  with_items:
    - conf.d
    - patterns.d

- name: Copy (and verify) Logstash filters.
  template:
    src: "{{ item.src }}"
    dest: "/etc/logstash/conf.d/{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
    validate: "/opt/logstash/bin/logstash --configtest -f %s"
  with_items: logstash_filters
  notify: restart logstash

- name: Copy Logstash patterns.
  template:
    src: "{{ item.src }}"
    dest: "/etc/logstash/patterns.d/{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items: logstash_patterns
  notify: restart logstash

- name: Enable logstash service.
  service:
    name: logstash
    state: running
    enabled: yes

