---
# tasks file for elk
- include: java.yml
  tags: java

- include: elasticsearch.yml
  tags: elasticsearch

- include: mappings.yml
  tags: mappings

- include: logstash.yml
  tags: logstash

- include: kibana.yml
  tags: kibana

- include: nginx.yml
  tags: nginx

- include: ufw.yml
  tags: ufw

- include: snapshot.yml
  when: elk_elasticsearch_snapshot == true
  tags: snapshot
