---
# The `uri` module requires httplib2, although allegedly Ansible v2.1 will drop the dependency.
# The "snapshot" task list in this role also calls `uri`.
- name: Install httplib2
  apt:
    name: python-httplib2
    state: present

- name: Set default ElasticSearch mappings for Logstash.
  uri:
    url: "http://localhost:9200/_template/logstash"
    method: POST
    body: "{{ lookup('file', 'elasticsearch-template-logstash-output.json') }}"
    status_code: 200
    body_format: json

- name: Set default ElasticSearch mappings for Topbeat.
  uri:
    url: "http://localhost:9200/_template/topbeat"
    method: POST
    body: "{{ lookup('file', 'elasticsearch-template-topbeat.json') }}"
    status_code: 200
    body_format: json

- name: Set default ElasticSearch mappings for Filebeat.
  uri:
    url: "http://localhost:9200/_template/filebeat"
    method: POST
    body: "{{ lookup('file', 'elasticsearch-template-filebeat.json') }}"
    status_code: 200
    body_format: json
