---
- name: Create ElasticSearch snapshot directory.
  file:
    path: "{{ elk_elasticsearch_snapshot_directory }}"
    state: directory
    mode: "0750"
    owner: elasticsearch
    group: elasticsearch

- name: Initialize ElasticSearch snapshot via API.
  uri:
    url: "http://localhost:9200/_snapshot/{{ elk_elasticsearch_snapshot_repository }}"
    method: PUT
    body: "{{ elk_elasticsearch_snapshot_initialization | to_json }}"

- name: Create new snapshot via API.
  uri:
    url: "http://localhost:9200/_snapshot/{{ elk_elasticsearch_snapshot_repository }}/{{ elk_elasticsearch_snapshot_name }}?wait_for_completion=true"
    method: PUT
  # Would be better to inspect the JSON returned by the request, but running `uri`
  # in this fashion is essentially the same as `command`, so reporting changed: true makes sense.
  changed_when: yes
