---
# handlers file for elk
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart logstash
  service:
    name: logstash
    state: restarted

- name: restart kibana
  service:
    name: kibana
    state: restarted

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: reload systemd
  command: /bin/systemctl daemon-reload

- name: restart ufw
  service:
    name: ufw
    state: restarted
